import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { ChevronDownIcon, ChevronUpIcon } from '@heroicons/react/24/outline';

interface Question {
  id: string;
  question: string;
  answer: string;
}

interface Section {
  id: string;
  title: string;
  questions: Question[];
}

// Exported so the prerenderer can build this page's FAQPage structured data from
// the same array the page renders. A hand-maintained second copy would drift the
// first time a question is edited, and structured data that disagrees with the
// visible page is worse than none.
export const sections: Section[] = [
  {
    id: 'general',
    title: 'General',
    questions: [
      {
        id: 'what-is-businesscart',
        question: 'What is BusinessCart.ai?',
        answer: 'BusinessCart.ai is an e-commerce platform that gives businesses their own branded online store, private commerce portal, and B2B tools, free to start with a $5 max platform fee per order, no matter the size. Every feature is included in every tier. No feature locks. There is no monthly fee at any volume: you pay 6% on your first 100 orders each month, 2% on orders 101 to 1,000, and 1% beyond that, never more than $5 per order.',
      },
      {
        id: 'who-is-it-for',
        question: 'Who is BusinessCart.ai for?',
        answer: 'Any business that sells products: restaurants, retail stores, wholesalers, distributors, manufacturers, D2C brands, and more. Whether you sell to consumers, other businesses, or both, the platform adapts to your model.',
      },
      {
        id: 'how-is-it-different',
        question: 'How is this different from Shopify or other platforms?',
        answer: 'Three main differences: (1) Free to start: the Starter tier is $0/month, you only pay when you sell. (2) No feature locks: every feature is in every tier; your monthly fee scales with your order volume, not with what features you need. (3) Speed: your storefront loads in under 1 second because it is generated as static HTML, not rendered by a JavaScript framework.',
      },
      {
        id: 'pricing',
        question: 'How much does it cost?',
        answer: 'No monthly fee, at any volume, and every feature is included at every volume. Pricing is per order and gets cheaper as you grow: 6% on your first 100 orders each month, 2% on orders 101 to 1,000, and 1% on order 1,001 onwards. Every order is capped at $5 no matter its size, so a $10,000 wholesale order costs $5 in fees. Each order is priced by its own position in the month, so growing never re-prices orders you have already taken. Connecting the other systems you run is included on every tier at no extra cost; if one of those systems charges for its own API access, you pay that vendor directly. 30-day money-back on Growth and Enterprise.',
      },
    ],
  },
  {
    id: 'for-companies',
    title: 'For Companies (Sellers)',
    questions: [
      {
        id: 'how-to-get-started',
        question: 'How do I get started as a company?',
        answer: 'Contact us at help@businesscart.ai with your company name and business email. We will create your account, give you a business code, and walk you through setup, from adding products to connecting your payment provider. Most companies are live within 30 minutes.',
      },
      {
        id: 'what-is-business-code',
        question: 'What is a business code?',
        answer: 'A business code is a unique identifier we provide to your company during onboarding. You use it to register your account on the platform. It links your account to your company profile, product catalog, and settings.',
      },
      {
        id: 'how-customers-find-me',
        question: 'How do my customers find and access my store?',
        answer: 'Two ways: (1) Your public D2C storefront, anyone can visit it and buy directly. It gets its own URL (yourcompany.businesscart.ai or your own custom domain). (2) The private portal: you give your customers a customer code, they register, and they see your private catalog with their personalized pricing.',
      },
      {
        id: 'customer-codes',
        question: 'What are customer codes?',
        answer: 'Customer codes are generated by you from your dashboard. You give them to your buyers so they can register and associate with your company. This gives them access to your private catalog with their specific pricing, payment methods, and delivery options.',
      },
      {
        id: 'per-customer-config',
        question: 'Can I set different prices for different customers?',
        answer: 'Yes. You can configure unique discount percentages, allowed payment methods, delivery options, order limits, spending caps, and credit limits for each customer. If a customer does not have a custom setting, your company defaults apply automatically.',
      },
      {
        id: 'payment-gateways',
        question: 'What payment methods can I accept?',
        answer: 'Stripe, Amazon Pay, and Authorize.net for online payments. For offline payments: pickup and pay, delivery and pay, and purchase orders. You connect your own payment provider. BusinessCart.ai never touches your money. Payments go directly to your account.',
      },
      {
        id: 'manage-products',
        question: 'How do I manage my products?',
        answer: 'From your dashboard, you can add, edit, and remove products with names, descriptions, prices, categories, images, stock quantities, and deal pricing. Product images are uploaded directly and served through a global CDN for fast loading.',
      },
      {
        id: 'quotes',
        question: 'How does quote negotiation work?',
        answer: 'A customer submits items for a quote. You can review, adjust prices, add comments, and counter-offer. The customer can accept, reject, or counter back. When both sides agree, the quote converts to an order. The full negotiation history is preserved.',
      },
      {
        id: 'suppliers-vendors',
        question: 'Can outside suppliers or vendors sell through my BusinessCart store?',
        answer: 'Yes. Register them as Partners with a partner code. They get their own login, add products to your catalog, and see the orders that contain their items. It is a drop-ship or consignment model: you own the brand, the storefront, and the customer relationship. They handle inventory. This is built-in, no plugin or third-party app needed. Split payouts, per-partner shipping tracking, and per-vendor returns are on the roadmap.',
      },
      {
        id: 'full-marketplace',
        question: 'Do you support a full multi-vendor marketplace with vendor storefronts and automated payouts?',
        answer: 'Not yet. What we support today is catalog-level: partners add products to your storefront, and they see the orders for their items. Vendor-branded storefronts, automated commission splits, per-vendor shipping tracking, and returns per vendor are on the roadmap. If you need those specific features today, tell us and we will scope them into the timeline.',
      },
      {
        id: 'wholesale-ordering-tools',
        question: 'What B2B ordering tools do my wholesale customers get?',
        answer: 'Several, all built in. Buyers get a Quick Order page (add by SKU with autocomplete, paste a list, upload a CSV, or use a browse grid) and can save up to 3 named carts per supplier to reorder in a click. You can set per-product case packs and order increments, so customers order in cases of 24 or pallets of 40. And you can generate a branded, printable or PDF line sheet of your catalog, curated by category or product. No app or plugin required.',
      },
      {
        id: 'staff-roles-costs',
        question: 'Can I let staff use the portal without showing them my costs and margins?',
        answer: 'Yes. Everyone you invite is an owner, an admin or staff. Staff run the day to day: orders, quotes, customers, and the product catalog. What they cannot see is what your goods cost you, so the Margin Report and every cost figure are blank for them, enforced by the API and not just hidden in the screen. Admins see costs and margins. Only you, the owner, can change payment gateway settings or see your billing statements, because whoever can rewrite a gateway secret can redirect the money your store takes.',
      },
      {
        id: 'seller-side-approvals',
        question: 'Can I require internal sign-off before a quote goes out to a customer?',
        answer: 'Yes, and this is rare: most B2B platforms only let the buying side approve. Set a threshold on order value or total quantity, then name who signs off inside your own company. When a rep approves a quote at or above it, the quote goes to your approver first and the customer sees nothing until your side has cleared it. You can have several levels, and several people on each level, so a quote does not stall because one person is away. Your customer never sees who your approvers are or what they wrote on a decision.',
      },
      {
        id: 'approval-audit-record',
        question: 'Is there a record of who approved what?',
        answer: 'Yes, and it cannot be edited or removed. Every decision records who made it, when, any note they left, and the order total at that moment. If a quote is withdrawn and reinstated, the earlier sign-offs stay on the record rather than being wiped. Overrides are recorded too: if you release an order without waiting for an approver, that is logged with your name and every approval level it skipped.',
      },
    ],
  },
  {
    id: 'for-customers',
    title: 'For Customers (Buyers)',
    questions: [
      {
        id: 'register-customer',
        question: 'How do I register as a customer?',
        answer: 'You need a customer code from the company you want to buy from. Enter it during registration along with your name and email. This links your account to that company and gives you access to their catalog with your personalized pricing.',
      },
      {
        id: 'multiple-companies',
        question: 'Can I buy from multiple companies?',
        answer: 'Yes. A single customer account can be associated with multiple companies. Each company relationship has its own pricing, payment methods, and delivery options. You switch between companies from one login.',
      },
      {
        id: 'how-to-order',
        question: 'How do I place an order?',
        answer: 'Browse the catalog, add items to your cart, and proceed to checkout. The system generates a quote with taxes and any discounts applied. Review the quote, select your payment and delivery method, and confirm. You receive an order confirmation with full details.',
      },
      {
        id: 'order-history',
        question: 'How do I view my past orders?',
        answer: 'Your complete order history is available from your account dashboard. You can view order details, status, and history across all companies you are associated with.',
      },
      {
        id: 'quick-order-reorder',
        question: 'Is there a faster way to place large or repeat orders?',
        answer: 'Yes. The Quick Order page lets you add items by SKU with autocomplete, paste a "SKU, quantity" list, upload a CSV, or browse a compact grid, then add everything to your cart at once. You can also save up to 3 named carts per supplier (requisition lists) and reload one to reorder in a click, and one-click reorder any past order from your history.',
      },
      {
        id: 'buyer-org-roles',
        question: 'Can colleagues in my company have different levels of access?',
        answer: 'Yes, and you set it up yourself rather than asking your supplier to. Colleagues who join with your invite code are owner, admin or staff. Everyone can order, subject to whatever approval rules you have set. Only you, as the owner, can change those approval rules, invite or remove colleagues, or change anyone\'s level. Your supplier cannot see or change any of it.',
      },
      {
        id: 'buyer-side-approvals',
        question: 'Can my company require approval before an order is placed?',
        answer: 'Yes, and you set it up yourself rather than asking your supplier to. Name who signs off inside your organisation and the threshold that triggers it, on order value or total quantity, and choose whether it applies to normal checkout, negotiated quotes, or both. Orders at or above the threshold are held until your approvers clear them, and any one person on a level can clear it so nothing waits on someone who is on leave. Your supplier cannot see or change your rules, and cannot see your approvers or the notes they write. Every decision is recorded permanently: who, when, the note, and the order total at the time.',
      },
    ],
  },
  {
    id: 'storefronts',
    title: 'D2C Storefronts',
    questions: [
      {
        id: 'what-is-storefront',
        question: 'What is a D2C storefront?',
        answer: 'Every company on BusinessCart.ai gets an automatically generated public online store. It displays your products with your branding, logo, and colors. Anyone can visit it and make a purchase. No portal registration needed.',
      },
      {
        id: 'storefront-speed',
        question: 'Why are the storefronts so fast?',
        answer: 'Storefronts are generated as pure static HTML. No JavaScript framework, no database queries at page load. They are served from a global content delivery network, which means pages load in under 1 second from anywhere in the world.',
      },
      {
        id: 'custom-domain',
        question: 'Can I use my own domain?',
        answer: 'Yes. By default, your storefront is available at yourcompany.businesscart.ai. You can also use your own domain (like www.yourstore.com) at no additional cost. We handle the SSL certificate and routing.',
      },
      {
        id: 'storefront-seo',
        question: 'Do storefronts include SEO?',
        answer: 'Yes. Every storefront automatically includes a sitemap, meta tags, OpenGraph tags for social sharing, and schema.org product markup for search engines. No plugins or configuration needed.',
      },
      {
        id: 'ai-ready',
        question: 'What does "AI-ready" mean?',
        answer: 'Your storefront is built as plain HTML that AI assistants like ChatGPT, Google, and Alexa can read directly. Most e-commerce platforms use JavaScript to render products, which AI cannot read. Your store is visible to the next generation of shopping: AI-powered discovery and voice search.',
      },
      {
        id: 'shopping-feeds',
        question: 'How do I list my products on Google Shopping, Facebook, Pinterest, etc.?',
        answer: 'Go to your company settings and enable the shopping channels you want. BusinessCart auto-generates product feeds for Google Shopping, Facebook/Instagram, Bing, Pinterest, and TikTok. Copy the feed URL and submit it to each channel\'s merchant center. Feeds update automatically whenever you update products. No apps, no plugins, no extra cost.',
      },
      {
        id: 'order-export',
        question: 'Can I export my orders for accounting or tax filings?',
        answer: 'Yes. From the Orders page, click Export, pick Generic CSV format, and choose your date range. The CSV includes order ID, date, status, customer email, payment and delivery method, subtotal, shipping, tax, grand total, item count, tracking, and ad click IDs. Suitable for monthly P&L, AR reconciliation, or tax filings. No app subscription, no extra cost.',
      },
      {
        id: 'ppc-conversions',
        question: 'How do I track Google Ads or Microsoft Ads conversions?',
        answer: 'Click IDs from paid ads (gclid, msclkid) are captured automatically when shoppers land on your storefront and stored on the resulting order. From the Orders page, click Export, pick Google Ads or Microsoft Ads format, choose a date range, and upload the CSV to Google Ads (Tools → Conversions → Uploads) or Microsoft Advertising (Tools → Bulk Operations → Upload bulk file). Bidding algorithms learn from real conversions within hours. No Zapier, no monthly app, no third-party tags.',
      },
    ],
  },
  {
    id: 'support',
    title: 'Support and Security',
    questions: [
      {
        id: 'contact-support',
        question: 'How do I contact support?',
        answer: 'Email us at help@businesscart.ai or call +1 (657) 501-0200. Our team is entirely US-based. You talk to the same people who build the platform. We respond within one business day.',
      },
      {
        id: 'data-security',
        question: 'How is my data secured?',
        answer: 'All data is transmitted over HTTPS/TLS. Payment gateway credentials are encrypted at rest using AES-256-GCM. Authentication uses JWT tokens with automatic expiration. The platform runs on cloud infrastructure with automated security updates. See our Privacy Policy for full details.',
      },
      {
        id: 'data-ownership',
        question: 'Who owns my data?',
        answer: 'You do. Your products, customers, orders, and business configuration belong to you. BusinessCart.ai hosts and processes your data to provide the service, but we do not claim ownership of it. If you close your account, we delete your data upon request.',
      },
    ],
  },
];

const FAQ: React.FC = () => {
  const [openQuestion, setOpenQuestion] = useState<string | null>(null);

  const toggleQuestion = (questionId: string) => {
    setOpenQuestion(openQuestion === questionId ? null : questionId);
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <Navbar />
      <main className="flex-grow">

        {/* Hero */}
        <div className="bg-gray-800 py-16 sm:py-20">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h1 className="text-3xl sm:text-4xl font-extrabold text-white">Frequently Asked Questions</h1>
            <p className="mt-4 text-lg text-gray-200 max-w-2xl mx-auto">
              Everything you need to know about the platform, for companies and customers.
            </p>
          </div>
        </div>

        {/* FAQ Sections */}
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="space-y-8">
            {sections.map((section) => (
              <div key={section.id} className="bg-white rounded-lg shadow-lg overflow-hidden">
                <div className="bg-gray-50 px-6 py-4 border-b border-gray-200">
                  <h2 className="text-lg font-semibold text-gray-900">{section.title}</h2>
                </div>
                <div className="divide-y divide-gray-100">
                  {section.questions.map((q) => (
                    <div key={q.id}>
                      <button
                        className="w-full text-left px-6 py-4 flex justify-between items-center hover:bg-gray-50 transition"
                        onClick={() => toggleQuestion(q.id)}
                      >
                        <span className="text-base font-medium text-gray-900 pr-4">{q.question}</span>
                        {openQuestion === q.id ? (
                          <ChevronUpIcon className="h-5 w-5 text-teal-700 flex-shrink-0" />
                        ) : (
                          <ChevronDownIcon className="h-5 w-5 text-gray-400 flex-shrink-0" />
                        )}
                      </button>
                      {/* Toggle the CLASS, never the mount. Conditional mounting kept
                          answers out of the prerendered DOM entirely (openQuestion is
                          null at build time), so the static HTML shipped questions with
                          no answers and faq.md gave AI crawlers a list of questions it
                          could not answer. The answers were reachable only inside the
                          FAQPage JSON-LD, which turndown skips because it is a script. */}
                      <div className={openQuestion === q.id ? 'px-6 pb-4' : 'hidden'}>
                        <p className="text-gray-600 leading-relaxed">{q.answer}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* Still have questions */}
          <div className="mt-12 text-center">
            <p className="text-gray-600 mb-4">Still have questions?</p>
            <Link
              to="/contact-us"
              className="inline-flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-teal-700 hover:bg-teal-800"
            >
              Contact Us
            </Link>
          </div>
        </div>

      </main>
      <Footer />
    </div>
  );
};

export default FAQ;
